insert into roles (nombre) values ("ROLE_USER");
insert into roles (nombre) values ("ROLE_ADMIN");
insert into usuarios (nombre, password, enabled) values ("admin" ,"$2a$10$8NsXOux0a0bjOtq0XwSTaOrUhO49AI04QBehuu0gsS.q4TntFXZ.y", true);
insert into usuarios (nombre, password, enabled) values ("registrado" ,"$2a$10$WK6zonfCqIONhtS4wG1EYOVILbgwybct3.z4ReJHsJmUXpYLAhkb2", true);
insert into usuarios (nombre, password, enabled) values ("adri" ,"$2a$10$RHJWcb33KGJu5HWC6DSiaex4B0e0b1FqhsmQopZ..g2zbziLBKsTS", true);
insert into usuariorol (idUsuario, idRol) values (1, 1);
insert into usuariorol (idUsuario, idRol) values (1, 2);
insert into usuariorol (idUsuario, idRol) values (2, 1);
insert into usuariorol (idUsuario, idRol) values (3, 2);
insert into pizza (sabor, precio,tiempo) values ("Cuatro quesos", 14, 30);
insert into pizza (sabor, precio,tiempo) values ("Barbacoa de pollo", 15, 30);
insert into pizza (sabor, precio,tiempo) values ("Cuatro estaciones", 16, 30);
insert into pizza (sabor, precio,tiempo) values ("Vegetal", 17, 30);
insert into pizza (sabor, precio,tiempo) values ("Especial Leonesa", 15, 30);
insert into pizza (sabor, precio,tiempo) values ("Especial Astur", 16, 30);
insert into pizza (sabor, precio,tiempo) values ("Tropical", 14, 30);
insert into pizza (sabor, precio,tiempo) values ("Bolognesa", 15, 30);
insert into pizza (sabor, precio,tiempo) values ("Barbacoa de Maiz", 16, 30);
insert into pizza (sabor, precio,tiempo) values ("Cabrini", 14, 30);
insert into pizza (sabor, precio,tiempo) values ("Carbonara", 15, 30);
insert into pizza (sabor, precio,tiempo) values ("Picara", 16, 30);